project/src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity]
#[ORM\Table(name: "author")]

class Author
{

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    #[ORM\Column(type: "integer")]

    public $id;

    #[ORM\Column(name: "first_name", type: "string", length: 255)]
    #[Assert\NotBlank()]

    public $firstName;

    #[ORM\Column(name: "last_name", type: "string", length: 255)]
    #[Assert\NotBlank()]
    public $lastName;

    #[ORM\Column(name: "middle_name", type: "string", length: 255)]
    #[Assert\NotBlank()]
    public $middleName;

    #[ORM\ManyToMany(targetEntity: "Book", mappedBy: "authors", cascade: ["persist"])]

    public $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    
    
    public function addBook(Book $book)
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this); // Assuming you have a method like this in the Book entity
        }
        $this->books[] = $book;
        $book->addAuthor($this);

        return $this;
    }
    /**
     * @return Collection|Book[]
     */

    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->removeElement($book)) {
            $book->removeAuthor($this); // Assuming you have a method like this in the Book entity
        }
        //$this->removeBook($book);
        $book->removeAuthor($this);
        

        return $this;
    }

    // Добавьте геттеры и сеттеры
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): string
    {
        return sprintf('%s %s %s', $this->firstName, $this->lastName, $this->middleName);
    }
}

project/src/Entity/Book.php
<?php
// src/Entity/Book.php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity]
#[ORM\Table(name: "book")]

class Book
{

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    #[ORM\Column(type: "integer")]

    public $id;

    #[ORM\Column(name: "title", type: "string", length: 255)]
    #[Assert\NotBlank()]
    public $title;

    #[ORM\Column(name: "year", type: "integer")]
    #[Assert\NotBlank()]
    public $year;

    #[ORM\Column(name: "isbn", type: "string", length: 255)]
    #[Assert\NotBlank()]
    public $isbn;

    #[ORM\Column(name: "page_count", type: "integer")]
    #[Assert\NotBlank()]
    public $pageCount;

    
    #[ORM\ManyToMany(targetEntity: Author::class, inversedBy: "books", fetch: "EXTRA_LAZY", cascade: ["persist"])]
    
    #[ORM\JoinTable(name: "author_book_association")]
    #[ORM\JoinColumn(name: "book_id", referencedColumnName: "id")]
    #[ORM\InverseJoinColumn(name: "author_id", referencedColumnName: "id")]
    public $authors;

   public function __construct()
   {
       $this->authors = new ArrayCollection();
   }

   
    

    public function addAuthor(Author $author)
    {
        if (!$this->authors->contains($author)) {
            $this->authors[] = $author;
            $author->addBook($this); // Assuming you have a method like this in the Author entity
        }
        // $author->addBook($this); 
        // $this->authors[] = $author;
            

        return $this;
    }

    /**
     * @return Collection|Author[]
     */

    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function removeAuthor(Author $author): self
    {
        if ($this->authors->removeElement($author)) {
            $author->removeBook($this); // Assuming you have a method like this in the Author entity
        }

        return $this;
    }

    // Добавьте геттеры и сеттеры
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return sprintf('%s (%d)', $this->title, $this->year);
    }
}

project/src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('year')
            ->add('isbn')
            ->add('pageCount')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

project/src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\Book2Type;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/book')]
class BookController extends AbstractController
{
    #[Route('/', name: 'app_book_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $books = $entityManager
            ->getRepository(Book::class)
            ->findAll();

        return $this->render('book/index.html.twig', [
            'books' => $books,
        ]);
    }

    #[Route('/new', name: 'app_book_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $book = new Book();
        $form = $this->createForm(Book2Type::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($book);
            $entityManager->flush();

            return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('book/new.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_book_show', methods: ['GET'])]
    public function show(Book $book): Response
    {
        return $this->render('book/show.html.twig', [
            'book' => $book,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_book_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Book $book, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Book2Type::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('book/edit.html.twig', [
            'book' => $book,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_book_delete', methods: ['POST'])]
    public function delete(Request $request, Book $book, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(), $request->request->get('_token'))) {
            $entityManager->remove($book);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_book_index', [], Response::HTTP_SEE_OTHER);
    }
}

project/templates/book/_delete_form.html.twig
<form method="post" action="{{ path('app_book_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn">Delete</button>
</form>

project/templates/book/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

project/templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Book{% endblock %}

{% block body %}
    <h1>Edit Book</h1>

    {{ include('book/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_book_index') }}">back to list</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}

project/templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book index{% endblock %}

{% block body %}
    <h1>Book index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Year</th>
                <th>ISBN</th>
                <th>Page Count</th>
                <th>Authors</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.year }}</td>
                <td>{{ book.isbn }}</td>
                <td>{{ book.pageCount }}</td>
                <td>
                        {% if book.authors is not empty %}
                            <ul>
                                {% for author in book.authors %}
                                    <li>{{ author.fullName }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            No authors
                        {% endif %}
                    </td>
                <td>
                    <a href="{{ path('app_book_show', {'id': book.id}) }}">show</a>
                    <a href="{{ path('app_book_edit', {'id': book.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_book_new') }}">Create new</a>
{% endblock %}

project/templates/book/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Book{% endblock %}

{% block body %}
    <h1>Create new Book</h1>

    {{ include('book/_form.html.twig') }}

    <a href="{{ path('app_book_index') }}">back to list</a>
{% endblock %}

project/templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book{% endblock %}

{% block body %}
    <h1>Book</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ book.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ book.title }}</td>
            </tr>
            <tr>
                <th>Year</th>
                <td>{{ book.year }}</td>
            </tr>
            <tr>
                <th>ISBN</th>
                <td>{{ book.isbn }}</td>
            </tr>
            <tr>
                <th>Page Count</th>
                <td>{{ book.pageCount }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_book_index') }}">back to list</a>

    <a href="{{ path('app_book_edit', {'id': book.id}) }}">edit</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}